---
- name: Create osprofiler system group
  group:
    name: "{{ osprofiler_system_user }}"
    state: "present"
    system: "yes"

- name: Create osprofiler system user
  user:
    name: "{{ osprofiler_system_user }}"
    group: "{{ osprofiler_system_user }}"
    shell: "/bin/sh"
    system: "yes"
    createhome: "yes"
    home: "/home/osprofiler"

- name: Creates osprofiler directory
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ osprofiler_system_user }}"
    group: "{{ osprofiler_system_user }}"
    mode: 0775
  with_items:
    - { path: "/src" }
    - { path: "/etc/osprofiler" }
    - { path: "/var/log/osprofiler" }
    - { path: "/var/run/osprofiler" }

- name: Clone the osprofiler repo
  git:
    repo: "https://github.com/sacharya/osprofiler.git"
    dest: "/src/osprofiler"
    update: yes

- name: Install profiler
  shell: |
    cd /src/osprofiler; pip install -r requiremnets; python setup.py install

- name: set facts for daemon
  set_fact:
    user: "{{ osprofiler_system_user }}"
    daemon: "/src/osprofiler/osprofiler/profile.py"
    pidfile: /var/run/osprofiler/osprofiler.pid
    daemon_opts: ""
    service_name: osprofilerd

- name: Copy the conf files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: 0751
  with_items:
    - src: osprofiler.conf.j2
      dest: /etc/osprofiler/osprofiler.conf
      owner: "{{ osprofiler_system_user }}"
      group: "{{ osprofiler_system_user }}"
    - src: init.d-template.j2
      dest: /etc/init.d/osprofilerd

- name: Ensure osprofiler daemon is started
  service:
    name: osprofilerd
    state: started
